Remove traling whitespace for now until we can fix it

diff --git a/.github/workflows/code-style.yaml b/.github/workflows/code-style.yaml
--- a/.github/workflows/code-style.yaml
+++ b/.github/workflows/code-style.yaml
@@ -157,34 +157,34 @@ jobs:
 
           echo '::endgroup::'
 
-      - name: trailing whitespace
-        shell: bash
-        if: ${{ always() }}
-        env:
-          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
-        run: |
-          set -e
-          cd "${GITHUB_WORKSPACE}" || exit 1
-
-          echo '::group:: Flagging trailing whitespace with reviewdog 🐶 ...'
-          # Don't fail because of grep
-          set +o pipefail
-
-          # Exclude generated and vendored files, plus some legacy
-          # paths until we update all .gitattributes
-          git ls-files |
-          git check-attr --stdin linguist-generated | grep -Ev ': (set|true)$' | cut -d: -f1 |
-          git check-attr --stdin linguist-vendored | grep -Ev ': (set|true)$' | cut -d: -f1 |
-          grep -Ev '^(vendor/|third_party/|.git|utils/)' |
-          xargs grep -nE " +$" |
-          reviewdog -efm="%f:%l:%m" \
-                -name="trailing whitespace" \
-                -reporter="github-pr-check" \
-                -filter-mode="added" \
-                -fail-on-error="true" \
-                -level="error"
-
-          echo '::endgroup::'
+#      - name: trailing whitespace
+#        shell: bash
+#        if: ${{ always() }}
+#        env:
+#          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
+#        run: |
+#          set -e
+#          cd "${GITHUB_WORKSPACE}" || exit 1
+#
+#          echo '::group:: Flagging trailing whitespace with reviewdog 🐶 ...'
+#          # Don't fail because of grep
+#          set +o pipefail
+#
+#          # Exclude generated and vendored files, plus some legacy
+#          # paths until we update all .gitattributes
+#          git ls-files |
+#          git check-attr --stdin linguist-generated | grep -Ev ': (set|true)$' | cut -d: -f1 |
+#          git check-attr --stdin linguist-vendored | grep -Ev ': (set|true)$' | cut -d: -f1 |
+#          grep -Ev '^(vendor/|third_party/|.git|utils/)' |
+#          xargs grep -nE " +$" |
+#          reviewdog -efm="%f:%l:%m" \
+#                -name="trailing whitespace" \
+#                -reporter="github-pr-check" \
+#                -filter-mode="added" \
+#                -fail-on-error="true" \
+#                -level="error"
+#
+#          echo '::endgroup::'
 
       - name: EOF newline
         shell: bash
